---
version: "2"

services:
  producer:
    build: ./producer
    volumes:
      - ./producer:/code
    ports:
      - "9090:9090"
    networks:
      - paper
  consumer:
    build: ./consumer
    depends_on:
      - producer
    volumes:
      - ./consumer:/code
    networks:
      - paper
    
networks:
  paper:
    driver: bridge